config/routes.rb
NjcBookclub::Application.routes.draw do
  get "books/index"
  get "books/manage"
  get "books/i_have_one"
  get "books/best_books"
  get "books/best_sharer"
  post "books/i_have_one"
  resources :books

  get "readings/index"
  get "readings/manage"
  resources :readings
  controller :readings do
    get "readings/manage" => :manage
  end

  controller :users do
    get "find_password" => :find_password
    post "reset_password" => :reset_password
  end

  resources :users
  resources :categories

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  controller :bookclub do
    get "bookclub" => :index    
    post "bookclub" => :index
    get "bookclub/show_books_by_category" => :index
    get "bookclub/show_books_by_query" => :index
    post "bookclub/show_books_by_query" => :index
    get "bookclub/show_books_by_owner" => :index
    get "bookclub/show_books_by_reader" => :index
    get "bookclub/show_suggested" =>:index
  end

  get "bookclub/index"
  get "bookclub/news"
  get "bookclub/billboard"
  get "bookclub/faq"
  get "bookclub/contact"
  get "bookclub/show_books_by_category"
  get "bookclub/show_books_by_owner"
  get "bookclub/show_books_by_query"
  post "bookclub/show_books_by_query"
  get "bookclub/show_books_by_reader"
  get "bookclub/show_suggested"
  get "bookclub/lend_book"
  post "bookclub/lend_book"

  root :to => "bookclub#index", :as => "bookclub"

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  RATING_NUMBERS = [ nil, 5.0, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0 ]

  belongs_to :resource
  belongs_to :book
  belongs_to :reader, :class_name => "User",
                      :foreign_key => "user_id"

  def reading_status()
    if status=="suggest"
      "SUGGEST"
    elsif read_at.nil?
      "RESERVED"
    elsif return_at.nil?
      "READING"
    else
      "RETURNED"
    end
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  skip_before_filter :authorize, :only => [ :show ]

  def index
    @readings = Reading.paginate(:include => [ :book, :reader ],
                                 :conditions => "(book_id is not null) and ( readings.status!='suggest' or readings.status is null )",
                                 :page=>params[:page],
                                 :order=>'read_at asc',
                                 :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @readings }
    end
  end

  def edit
    @reading = Reading.find(params[:id])
    unless validate_permission?(@reading.reader)
      redirect_to(readings_manage_path,
                  :notice => "无权编辑该借阅信息！")
    end
  end

  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reading }
    end
  end

  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to(readings_manage_path, :notice => '借阅更新成功！') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reading.errors, :status => :unprocessable_entity }
      end
    end
  end 

  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to session[:prev_url] }
      format.xml  { head :ok }
    end
  end

  def manage
    user_id = session[:user_id]
    if user_id
      @reader = User.find_by_id(user_id)
      @in_readings = Reading.find(:all,
                                  :conditions => [ "(book_id is not null) and (status != 'suggest' or status is null) and" +
                                                   " user_id = ?", user_id ],
                                  :include => [ :book, :resource ],
                                  :order => 'read_at desc')

      @out_readings = Reading.find(:all,
                                   :select => "r.*",
                                   :joins => " as r inner join resources as res" +
                                             " on res.id = r.resource_id",
                                   :conditions => [ "r.book_id is not null and (status != 'suggest'  or status is null ) and" +
                                                    " res.user_id = ?", user_id ],
                                   :include => [ :book, :reader ],
                                   :order => 'updated_at desc')

      respond_to do |format|
        format.html # manage.html.erb
        format.xml  { render :xml => @readings }
      end
    end
  end
end

app/views/readings/_form.html.erb
<div class="bookclub_form">

<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend><%= @reading.book.title %></legend>

  <div class="field">
    <%= f.label :rating %>
    <%= f.select :rating, Reading::RATING_NUMBERS %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
 <div class="actions">
    <%= f.submit %>
  </div>

 </fieldset>
<% end %>

</div>

app/views/readings/edit.html.erb
<h1>评价借阅</h1>

<%= render 'form' %>

app/views/readings/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div id="reading_list">
  <h1>图书借阅列表</h1>

<p><%= will_paginate @readings %></p>

  <table>
    <td>图书名称</td>
    <td>web id</td>
    <td>状态</td>
    <td>借阅时间</td>
    <td>归还时间</td>
    <td>评分</td>
    <td>评注</td>

    <% @readings.each do |reading| %>
    <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">

      <td><%=h reading.book.title %></td>
      <td><%=h reading.reader.webid %></td>
      <td><%=h reading.status %></td>
      <td><%=h (reading.read_at || "").to_date %></td>
      <td><%=h (reading.return_at || "").to_date %></td>
      <td><%=h reading.rating %></td>
      <td><%=h reading.comment %></td>

    </tr>
    <% end %>
  </table>
</div>

<br />

<p><%= will_paginate @readings %></p>

app/views/readings/manage.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div id="reading_list">
<% if @in_readings.count > 0 || @out_readings.count > 0 %>
  <h1><%= @reader.name %> 的图书借阅管理</h1>

<% if @out_readings.count > 0 %>
  <h3>借出图书列表</h3>
  <table>
    <td>图书名称</td>
    <td>借阅者</td>
    <td>状态</td>
    <td>借阅时间</td>
    <td>归还时间</td>
    <td>评分</td>
    <td>评注</td>
    <td>创建时间</td>
    <td>更新时间</td>

    <% @out_readings.each do |reading| %>
    <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">

      <td><%=h reading.book.title %></td>
      <td>
        <% if reading.reader %>
        <%=h reading.reader.webid %>
        <% end %>
      </td>
      <td>
      <% case reading.reading_status %>
        <% when "RESERVED" %>
        预借
        <% when "READING" %>
        已借出
        <% when "RETURNED" %>
        已归还
      <% end %>
      </td>
      <td><%=h (reading.read_at || "").to_date %></td>
      <td><%=h (reading.return_at || "").to_date %></td>
      <td><%=h reading.rating %></td>
      <td><%=h reading.comment %></td>
      <td><%=h (reading.created_at || "").to_date %></td>
      <td><%=h (reading.updated_at || "").to_date %></td>

      <td>
      <% if !reading.read_at %>
        <%= button_to "借出", { :controller => :bookclub,
                               :action => "lend_book",
                               :lend => "lend_out",
                               :id => reading },
                             :confirm => "确认借出？" %>
      <% elsif !reading.return_at %>
        <td>
        <%= button_to "确认归还", { :controller => :bookclub,
                                  :action => "lend_book",
                                  :lend => "return",
                                  :id => reading },
                                  :confirm => "确认已归还？" %>
        </td>
      <% end %>
      </td>
    </tr>
    <% end %>
  </table>
<% end %>
  <h3>借阅图书列表</h3>
  <table>
    <td>图书名称</td>
    <td>拥有者</td>
    <td>状态</td>
    <td>借阅时间</td>
    <td>归还时间</td>
    <td>评分</td>
    <td>评注</td>
    <td>创建时间</td>
    <td>更新时间</td>

    <% @in_readings.each do |reading| %>
    <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">

      <td><%=h reading.book.title %></td>

      <% if reading.resource %>
        <td>
          <% if reading.resource.owner %>
          <%=h reading.resource.owner.webid %>
          <% end %>
        </td>
      <% else %>
        <td>N/A</td>
      <% end %>

      <td>
      <% case reading.reading_status %>
        <% when "RESERVED" %>
        预借
        <% when "READING" %>
        阅读中
        <% when "RETURNED" %>
        已归还
      <% end %>
      </td>
      <td><%=h (reading.read_at || "").to_date %></td>
      <td><%=h (reading.return_at || "").to_date %></td>
      <td><%=h reading.rating %></td>
      <td><%=h reading.comment %></td>
      <td><%=h (reading.created_at || "").to_date %></td>
      <td><%=h (reading.updated_at || "").to_date %></td>

      <td>
      <% if !reading.read_at %>
        <%= button_to "撤消", { :controller => :bookclub,
                             :action => "lend_book",
                             :lend => "cancel",
                             :id => reading },
                           :confirm => "确认撤消？" %>

      <% else %>
        <%= link_to "评价", edit_reading_path(reading) %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </table>
<% end %>

</div>

<br />