config/routes.rb
NjcBookclub::Application.routes.draw do
  get "books/index"
  get "books/manage"
  get "books/i_have_one"
  get "books/best_books"
  get "books/best_sharer"
  post "books/i_have_one"
  resources :books

  get "readings/index"
  get "readings/manage"
  resources :readings
  controller :readings do
    get "readings/manage" => :manage
  end

  controller :users do
    get "find_password" => :find_password
    post "reset_password" => :reset_password
  end

  resources :users
  resources :categories

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  controller :bookclub do
    get "bookclub" => :index    
    post "bookclub" => :index
    get "bookclub/show_books_by_category" => :index
    get "bookclub/show_books_by_query" => :index
    post "bookclub/show_books_by_query" => :index
    get "bookclub/show_books_by_owner" => :index
    get "bookclub/show_books_by_reader" => :index
    get "bookclub/show_suggested" =>:index
  end

  get "bookclub/index"
  get "bookclub/news"
  get "bookclub/billboard"
  get "bookclub/faq"
  get "bookclub/contact"
  get "bookclub/show_books_by_category"
  get "bookclub/show_books_by_owner"
  get "bookclub/show_books_by_query"
  post "bookclub/show_books_by_query"
  get "bookclub/show_books_by_reader"
  get "bookclub/show_suggested"
  get "bookclub/lend_book"
  post "bookclub/lend_book"

  root :to => "bookclub#index", :as => "bookclub"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :resources,    :dependent => :delete_all
  has_many :books,        :through => :resources,
                          :source => :book,
                          :readonly => true

  has_many :readings,     :dependent => :nullify
  has_many :read_books,   :through => :readings,
                          :source => :book,
                          :readonly => true

  composed_of :name, :class_name => "Name",
                     :mapping =>
                        [ # database    ruby
                         %w[ first_name first ],
                         %w[ initials   initials ],
                         %w[ last_name  last ]
                        ]

  attr_accessor :password_confirmation
  attr_reader   :password

  after_destroy :ensure_an_admin_remains

  validates :webid, :presence => true, :uniqueness => true
  validates :email, :presence => true
  validates :password, :confirmation => true
  #validates_format_of  :email, :message => "Email with incorrect Format", :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i  
  validates_format_of  :email, :message => "Email with incorrect Format", :with => /\A([^@\s]+)@(alcatel-lucent.com)/i  
  validate  :password_must_be_present

  @@domain="alcatel-lucent.com"
  def User.authenticate(webid, password)
    if user = find_by_webid(webid)
      salt = user.hashed_password[0, 2]      
      if user.hashed_password == encrypt_password(password, salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    # Data_Encryption_Standard
    password.crypt(salt)
  end

  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      salt = rand(100).to_s[0, 2]
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

private
  def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [ :show, :new, :create, :find_password, :reset_password ]

  # GET /users
  # GET /users.xml
  def index
    # Do not show all the users except the login user

    # @users = User.paginate :page=>params[:page], :order=>'webid asc',
    #   :per_page => 20

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.xml  { render :xml => @users }
    # end

    redirect_to :controller => "users",
                :action => "show",
                :id => session[:user_id]
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    unless validate_permission?(@user)
      redirect_to(user_path(@user),
                  :notice => "无权编辑该用户信息！")
    end
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    #@user.email+="@alcatel-lucent.com"

    respond_to do |format|
      if @user.save
        # send welcome email
        Mailer.welcome(@user).deliver

        format.html { redirect_to(users_url,
                                  :notice => 'User #{@user.id} was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(user_path(@user),
                                  :notice => "用户 #{@user.webid} 更新成功！") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])

    begin
      unless validate_permission?(@user)
        raise "无权删除该用户！"
      else
        @user.destroy
        flash[:notice] = "User #{@user.id} deleted"
      end
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def find_password
  end

  def reset_password
    @user = User.find_by_webid(params[:webid])

    if @user.nil?
      redirect_to(find_password_path,
                  :alert => "该web id不存在！")
    elsif @user.email.nil?
      redirect_to(find_password_path,
                  :alert => "该用户邮箱信息错误，请联系管理员！")
    else
      password = rand(1000000).to_s[0, 6]
      @user.password = password

      unless @user.save
        redirect_to(find_password_path,
                    :alert => "用户 #{@user.webid} 密码重置失败！")
      else
        # send email with new password
        Mailer.reset_password(@user, password).deliver
        
        redirect_to(login_path,
                    :alert => "用户 #{@user.webid} 密码重置成功！")
      end
    end
  end

end

app/views/users/_form.html.erb
<div class="bookclub_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        导致保存失败：</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <fieldset>
  <legend>输入用户详细信息</legend>

  <div>
    <label>web id</label>:
    <% unless @user.webid? %>
    <%= f.text_field :webid %>
    <% else %>
    <%= f.text_field :webid, :readonly => true %>
    <% end %>
  </div>

  <div>
    <label>密码</label>:
    <%= f.password_field :password, :size => 40 %>
  </div>

  <div>
    <label>密码确认</label>:
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>

  <div>
    <label>姓氏</label>:
    <%= f.text_field :last_name %>
  </div>

  <div>
    <label>名字</label>:
    <%= f.text_field :first_name %>
  </div>

  <div>
    <label>邮箱</label>:
    <%= f.text_field :email %> please use company email : xxx@alcatel-lucent.com
  </div>

  <div>
    <label>电话</label>:
    <%= f.text_field :phone_number %>
  </div>

  <div>
    <label>座位号</label>:
    <%= f.text_field :address %>
  </div>

  <div>
    <label></label>
  </div>

  <div>
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/edit.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>编辑用户</h1>

<%= render 'form' %>

<%= link_to '显示', @user %>

app/views/users/find_password.html.erb
<div class="bookclub_form">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>

  <p>注意：请勿错填webid，密码会重置并发至用户注册邮箱</p>

  <fieldset>
    <legend>重置密码</legend>

    <div>
      <label for="webid">web id</label>
    </div>

    <div>
      <%= form_tag({:controller => "users",
                    :action => "reset_password"},
                    :method => "post") do %>
      <%= text_field_tag :webid %>
    </div>

    <div>
      <label></label>
    </div>

    <div>
      <%= submit_tag "提交" %>
      <% end %>
    </div>

  </fieldset>

</div>

app/views/users/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>用户列表</h1>

<table>
  <tr>
    <th>web id</th>
    <th>名字</th>
    <th></th>
  </tr>

<p><%= will_paginate @books %></p>

<% @users.each do |user| %>
  <tr>
    <td><%= user.webid %></td>
    <td><%= user.name %></td>
    <td><%= link_to '显示', user %></td>
    <td><%= link_to '编辑', edit_user_path(user) %></td>
    <td><%= link_to '删除', user, :confirm => '确定删除用户?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新建用户', new_user_path %>

<p><%= will_paginate @books %></p>

app/views/users/new.html.erb
<h1>新建用户</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1><%= @user.name %> 的用户信息
<% if validate_permission?(@user) %>
  <%= link_to '编辑', edit_user_path(@user) %>
<% end %>
</h1>

<p>
  <b>web id:</b>
  <%= @user.webid %>
</p>

<p>
  <b>名字:</b>
  <%= @user.name %>
</p>

<p>
  <b>邮箱:</b>
  <%= @user.email %>
</p>

<p>
  <b>电话:</b>
  <%= @user.phone_number %>
</p>

<p>
  <b>座位号:</b>
  <%= @user.address %>
</p>

<p>
  <b>
  <%= link_to "拥有的图书", :controller => "bookclub",
              :action => "show_books_by_owner",
              :owner => @user
  %>
  <%= link_to "借阅历史", :controller => "bookclub",
              :action => "show_books_by_reader",
              :reader => @user
  %><br />
  </b>
</p>