config/routes.rb
NjcBookclub::Application.routes.draw do
  get "books/index"
  get "books/manage"
  get "books/i_have_one"
  get "books/best_books"
  get "books/best_sharer"
  post "books/i_have_one"
  resources :books

  get "readings/index"
  get "readings/manage"
  resources :readings
  controller :readings do
    get "readings/manage" => :manage
  end

  controller :users do
    get "find_password" => :find_password
    post "reset_password" => :reset_password
  end

  resources :users
  resources :categories

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  controller :bookclub do
    get "bookclub" => :index    
    post "bookclub" => :index
    get "bookclub/show_books_by_category" => :index
    get "bookclub/show_books_by_query" => :index
    post "bookclub/show_books_by_query" => :index
    get "bookclub/show_books_by_owner" => :index
    get "bookclub/show_books_by_reader" => :index
    get "bookclub/show_suggested" =>:index
  end

  get "bookclub/index"
  get "bookclub/news"
  get "bookclub/billboard"
  get "bookclub/faq"
  get "bookclub/contact"
  get "bookclub/show_books_by_category"
  get "bookclub/show_books_by_owner"
  get "bookclub/show_books_by_query"
  post "bookclub/show_books_by_query"
  get "bookclub/show_books_by_reader"
  get "bookclub/show_suggested"
  get "bookclub/lend_book"
  post "bookclub/lend_book"

  root :to => "bookclub#index", :as => "bookclub"

end

app/models/book.rb
class Book < ActiveRecord::Base
  LANGUAGE_TYPES = [ nil, "中文", "英文", "混合", "其它" ]

  has_and_belongs_to_many :categories,
                          :join_table => "categories_books"
  has_and_belongs_to_many :authors,
                          :join_table => "authors_books"

  has_many :resources,    :dependent => :delete_all
  has_many :owners,       :through => :resources,
                          :source => :owner,
                          :readonly => true

  has_many :readings,     :dependent => :nullify
  has_many :readers,      :through => :readings,
                          :source => :reader,
                          :readonly => true # attention: how to use

  has_many :attr_entries, :dependent => :delete_all
  has_one  :rating,       :through => :attr_entries,
                          :source => :attr,
                          :source_type => "BookRating",
                          :dependent => :delete
  #before_destroy :clear_book

  validates :title, :presence => true

  def quantity
    resources.collect {|x| x.current_quantity}.sum
  end

  def total_quantity
    resources.collect {|x| x.total_quantity}.sum
  end

  def clear_book(book)
     Reading.destroy_all "book_id = #{book.id}" 
     Resource.destroy_all "book_id = #{book.id}" 
  end
end

app/controllers/books_controller.rb
# -*- coding: utf-8 -*-
class BooksController < ApplicationController
  skip_before_filter :authorize, :only => [ :show ]

  def index
    manage

    ## below code will show all books
    # @books = Book.paginate :page=>params[:page], :order=>'id asc',
    #   :per_page => 20

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.xml  { render :xml => @books }
    # end
  end

  def best_books
  end

  def show_suggested
  end

  def best_sharer
  end

  def show
    @book = Book.find(params[:id],
                      :include => [ :owners ])
    
    @readings = Reading.paginate(:conditions => [ "book_id = ?",
                                                  @book.id
                                                ],
                                 :include => [ :reader ],
                                 :page => params[:page],
                                 :order => 'id asc',
                                 :per_page => 20)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def new
    @book = Book.new(params[:product])
    @category_options = Category.all
    @category = nil

    flash[:suggest]='1' if params[:suggest]=="1"
    puts "new book"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def edit
    @book = Book.find(params[:id],
                      :include => :categories)
    @category_options = Category.all
    @category = @book.categories.first

    unless validate_permission?(@book.owners)
      redirect_to(book_path(@book),
                  :notice => "无权编辑该图书信息！")
    end
  end

  def create
    @book = Book.new(params[:book])
    category = Category.find_by_id(params[:book_category])
    @book.categories << category
    @category_options = Category.all

    respond_to do |format|
      # for book be suggested to buy, set quantity to zero
      if add_book(flash[:suggest] =="1" )
        format.html { redirect_to(@book, :notice => "新书添加成功！") }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new", :notice => flash[:notice], :suggest=>"1" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        category = Category.find_by_id(params[:book_category])
        if @book.categories.first != category
          @book.categories.clear
          @book.categories << category

          # if a book's category is updated to 13 (suggested to buy),
          # then its resources should be cleared
          if category.id == 13
            @book.resources.each do |r|
              # destroy readings of this resource, since they are invalid
              r.readings.each do |reading|
                reading.destroy
              end
              r.destroy
            end
          end

          @book.save
        end

        format.html { redirect_to(@book, :notice => "图书更新成功！") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # set the total_quantity of resource to 0,
  # not really delete the book
  def destroy
    @book = Book.find(params[:id])
    # @book.destroy
    resource = Resource.first(:conditions => [ "user_id = ? and book_id = ?",
                                               session[:user_id],
                                               @book.id ])
    if ( resource.total_quantity > 1 )
	resource.total_quantity-=1
	resource.current_quantity-=1
        resource.save
    else 
	resource.delete
    end

    if  @book.total_quantity == 0 
	puts "deleting the book "
	@book.delete
    end


    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end

  def manage
    user_id = session[:user_id]

    if user_id
      @owner = User.find_by_id(user_id)
      @books = @owner.books.paginate(:include => :rating,
                                     :page => params[:page],
                                     :order => 'id desc',
                                     :per_page => 20)
    end
    render :action => "index"
  end

  def i_have_one
    @book = Book.find(params[:id])

    add_book
    redirect_to :action => "index"
  end

protected
  def add_book(suggest=false)
    book_id = nil
puts "#{suggest}"

    if @book.isbn.nil? || @book.isbn.empty?
      book = Book.find(:first, :conditions => [ "title = ?",
                                                @book.title ])
    else
      book = Book.find(:first, :conditions => [ "title = ? and isbn = ?",
                                                @book.title, @book.isbn ])
    end

    # book already exists
    # 1. the user already has a resource of the book
    # 2. a new resource needs be create
    if book
      resource = Resource.find(:first, :conditions => [ "book_id = ? and ( user_id = ? or total_quantity=0)",
                                book.id, session[:user_id] ])
      book_id = book.id

      # if the book already existed, and someone suggest to buy one 
      if suggest
	flash[:notice]="book existed"
puts "book existed"
	return false
      end

      if  book.status == "suggest" 
        book.status = "added"
        book.save
      end
    else
      @book.status="suggest" if suggest 
      unless @book.save
        return false
      end
      book_id = @book.id
    end

    if suggest 
        resource = Resource.new(:user_id => session[:user_id],
                                :book_id => book_id,
                                :current_quantity => 0,
                                :total_quantity => 0)

    else
      if resource
        if  resource.total_quantity==0
          resource.user_id=session[:user_id]
        end
        resource.current_quantity += 1
        resource.total_quantity   += 1
      else
        resource = Resource.new(:user_id => session[:user_id],
                                :book_id => book_id,
                                :current_quantity => 1,
                                :total_quantity => 1)
      end
    end

    resource.save

    if suggest
        time = Time.now
        sugg = Reading.new(:resource_id => resource.id,
                           :book_id => book_id,
                           :user_id => session[:user_id],
                           :created_at => time,
                           :updated_at => time,
                           :read_at => time,
                           :return_at => time,
                           :status=>"suggest")
        sugg.save
    end

    return true
  end
end

app/views/books/_form.html.erb
<div class="bookclub_form">

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %>导致保存失败：</h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>输入图书详细信息</legend>

  <div class="field">
    <label>书名</label>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <label>ISBN</label>
    <%= f.text_field :isbn %>
  </div>

  <div class="field">
    <label>类型</label>
    <% if @category %>
    <% cate_id = @category.id %>
    <% end %>
    <%= select_tag "book_category",
        options_from_collection_for_select(@category_options,
        "id", "name", cate_id) %>
  </div>

  <div class="field">
    <label>语言</label>
    <%= f.select :language, Book::LANGUAGE_TYPES %>
  </div>

  <div class="field">
    <label>价格</label>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <label>链接</label>
    <%= f.text_field :web_url %>
  </div>

  <div class="field">
    <label>描述</label>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/books/best_books.html.erb
It's under developing

app/views/books/best_sharer.html.erb
It's under developing...

app/views/books/edit.html.erb
<h1>编辑图书</h1>

<%= render 'form' %>

<%= link_to '显示', @book %> |
<%= link_to '返回', books_path %>

app/views/books/index.html.erb
<div id="book_list">
  <h1>图书列表</h1>

  <%= link_to '添加图书', new_book_path %>
  <%= link_to '建议购买', new_book_path(:suggest=>1) %>

  <table>
    <% @books.each do |book| %>
    <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
      <td class="list-description">
        <dl>
          <dt><%=h book.title %></dt>
          <dd><%=h truncate(book.description.gsub(/<.*?>/, ''),
                   :length => 80) %></dd>
        </dl>
      </td>

      <td class="list-actions">
        <%= link_to '显示', book %><br />
        <%= link_to '编辑', edit_book_path(book) %><br />
        <%= button_to '删除我的资源', book, :method => :delete, :confirm => "确认删除图书?" %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

<br />

<p><%= will_paginate @books %></p>

app/views/books/new.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>新建图书</h1>

<%= render 'form' %>

<%= link_to '返回', books_path %>

app/views/books/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <% if @book.image_url %>
    <%= link_to image_tag(@book.image_url, :border => 0) %>
  <% end %>
</p>

<p>
  <b>书名:</b>
  <font size=4><%= @book.title %> </font>
</p>

<br />

<p>
  <b>剩余数目:</b>
  <%= @book.quantity %>
</p>
<div class="lend-line">
      <% if @book.total_quantity <= 0 %>
        不可借
      <% elsif @book.quantity > 0 %>
        <%= button_to "借阅", { :controller => :bookclub,
                               :action => "lend_book",
                               :lend => "lend_in",
                               :id => @book },
				:onclick => "return confirm('确认借阅?')",
                             :style=>"color:blue;font:bold 15px Arial; height:30px;width:90px" %>
      <% else %>
        <%= button_to "预借", { :controller => :bookclub,
                               :action => "lend_book",
                               :lend => "reserve",
                               :id => @book },
                             :confirm => "确认预借?" %>
      <% end %>
</div>

<br />

<p>
  <b>ISBN:</b>
  <%= @book.isbn %>
</p>

<p>
  <b>语言:</b>
  <%= @book.language %>
</p>

<p>
  <b>价格:</b>
  <%= @book.price %>
</p>

<p>
  <b>链接:</b>
  <%= link_to_unless @book.web_url.nil?, h(@book.web_url), @book.web_url %>
</p>

<p>
  <b>描述:</b>
  <%= @book.description %>
</p>

<p>
  <% if @book.status == "suggest" %>
  <%= button_to "新书上架", { :controller => "books",
                                              :action => "i_have_one",
                                              :id => @book.id },
                                              :confirm => "新书已经可以借阅了?" %>
  <%else%>
  <b>拥有者:</b>
  <table>
  <% @book.owners.each do |o| %>
  <tr>
    <td><%= link_to o.name, user_path(o) %></td>
    <td>
    <%= link_to "拥有的图书", :controller => "bookclub",
                            :action => "show_books_by_owner",
                            :owner => o %>
    </td>
  </tr>
  <% end %>
  </table>


  <br />
  <%= button_to "我有一本", { :controller => "books",
                                              :action => "i_have_one",
                                              :id => @book.id },
                                            :confirm => "你有相同的书可供借阅?" %>

  <br />
  <%end%>

</p>

<p>
  <b>借阅历史:</b>
  <table>
  <% @readings.each do |r| %>
  <tr>
    <td>
      <% if r.reader %>
        <%= link_to r.reader.name, user_path(r.reader) %>
      <% end %>
    </td>
    <td>
    <%= link_to "拥有的图书", :controller => "bookclub",
                            :action => "show_books_by_owner",
                            :owner => r.reader %>
    </td>
    <td>
      <% case r.reading_status %>
        <% when "RESERVED" %>
        预借
        <% when "READING" %>
        阅读中
        <% when "RETURNED" %>
        已归还
        <% when "SUGGEST" %>
        建议购买
      <% end %>
    </td>
    <td><%= r.rating %></td>
    <td><%= r.comment %></td>
  </tr>
  <% end %>
  </table>
  <br />
</p>

<p><%= will_paginate @readings %></p>

app/views/books/show_suggested.html.erb
It's under developing ...