config/routes.rb
NjcBookclub::Application.routes.draw do
  get "books/index"
  get "books/manage"
  get "books/i_have_one"
  get "books/best_books"
  get "books/best_sharer"
  post "books/i_have_one"
  resources :books

  get "readings/index"
  get "readings/manage"
  resources :readings
  controller :readings do
    get "readings/manage" => :manage
  end

  controller :users do
    get "find_password" => :find_password
    post "reset_password" => :reset_password
  end

  resources :users
  resources :categories

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  controller :bookclub do
    get "bookclub" => :index    
    post "bookclub" => :index
    get "bookclub/show_books_by_category" => :index
    get "bookclub/show_books_by_query" => :index
    post "bookclub/show_books_by_query" => :index
    get "bookclub/show_books_by_owner" => :index
    get "bookclub/show_books_by_reader" => :index
    get "bookclub/show_suggested" =>:index
  end

  get "bookclub/index"
  get "bookclub/news"
  get "bookclub/billboard"
  get "bookclub/faq"
  get "bookclub/contact"
  get "bookclub/show_books_by_category"
  get "bookclub/show_books_by_owner"
  get "bookclub/show_books_by_query"
  post "bookclub/show_books_by_query"
  get "bookclub/show_books_by_reader"
  get "bookclub/show_suggested"
  get "bookclub/lend_book"
  post "bookclub/lend_book"

  root :to => "bookclub#index", :as => "bookclub"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NjcBookclub</title>
  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag :all %>
  <!%= javascript_include_tag 'jquery-1.10.2.js', 'application.js' %>
  <%= csrf_meta_tag %>
</head>
<body id="bookclub">
  <div id="banner">
    <%= link_to image_tag("logo.png", :border => 0),
                :controller => "bookclub",
                :action  => "index" %>
    <%= @page_title || "南京阿尔卡特朗讯图书借阅系统" %>
  </div>
  <div id="columns">
    <div id="side">

      <%= link_to '主页',     :controller => "bookclub",
                             :action => "index"%><br />
      <%= link_to '常见问题',  :controller => "bookclub",
                             :action => "faq"%><br />
      <%= link_to '联系我们',  :controller => "bookclub",
                             :action => "contact"%><br />
       <%= link_to '热门书籍',     :controller => "books",
                             :action => "best_books"%><br />
       <%= link_to '需求查询',     :controller => "bookclub",
                             :action => "index", :show_suggest=>"yes" %><br />
       <%= link_to '分享排行',     :controller => "books",
                             :action => "best_sharer"%><br />

      <% if session[:user_id] %>
        <br />
        <%= link_to '注销', logout_path, :method => :delete %><br />
        <%= link_to '账号管理', :controller => "users",
                              :action => "show",
                              :id => session[:user_id] %><br />
      <% else %>
        <br />
        <%= link_to '登录', login_path %><br />
        <%= link_to '注册', :controller => "users",
                           :action => "new" %><br />
      <% end %>
      
      <%= link_to '图书管理', :controller => "books",
                            :action => "manage" %><br />
      <%= link_to '借阅管理', :controller => "readings",
                            :action => "manage" %><br />
      <br />

      <div id="query">
        <table>
          <tr>
            <%= form_tag({:controller => "bookclub",
                         :action => "show_books_by_query"},
                         :method => "get") do %>
            <td><%= text_field_tag(:query_str,
                                   @query_str,
                                   :size => 12) %></td>
            <td><%= submit_tag("搜索") %></td>
            <% end %>
          </tr>
        </table>
      </div>

      <% if @categories %>
      <br />
      <div id="category">
        <div class="category_title">图书种类</div>
        <table>
          <%= render @categories %>
        </table>
      </div>
      <br />
      <% end %>



    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>